name: CI

on:
  pull_request:
    branches:
      - master
      
jobs:
  tym-ci:
    runs-on: macOS-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache RubyGems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Install dependencies
        run: sh ./bootstrap.sh

      - name: Run Tests
        run: bundle exec fastlane test